openapi: 3.0.0
info:
  version: "1.1"
  title: >-
    API para interconectar la información de declaraciones del panel de captura desplegado por la SESNA.
paths:
  /v1/spic:
    post:
      tags:
        - spic
      summary: API para interconectar Declaraciones patrimoniales.
      operationId: post_spic
      requestBody:
        description: JSON para peticiones de busqueda avanzada
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reqSpic'
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resSpic'
        '400':
          description: Página inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resError'
        '401':
          description: No tienes permisos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resError'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resError'
      security:
        - spic_auth: []
externalDocs:
  description: Más información.
  url: 'https://github.com/PDNMX/api_docs'
components:
  securitySchemes:
    spic_auth:
      type: oauth2
      flows:
        password:
          tokenUrl: /oauth
          scopes: {}
  schemas:
    resSpic:
      type: object
      required:
        - pagination
        - results
      properties:
        pagination:
          type: object
          required:
            - pageSize
            - page
            - totalRows
            - hasNextPage
          properties:
            pageSize:
              type: integer
              minimum: 1
              description: 'Número de registros mostrados, por defecto muestra diez.'
              example: 100
            page:
              type: integer
              minimum: 1
              description: Número de página actual
              example: 20
            totalRows:
              type: integer
              minimum: 1
              description: Total de registros
              example: 30
            hasNextPage:
              type: boolean
              description: Indica si existe otra página
              example: true  
        results:
          $ref: '#/components/schemas/respSpic'
   